@startuml
skinparam backgroundColor transparent
boundary AccDesignPage
entity DesignOrder
control Notification

(AccDesignPage) -> (DesignOrder): updateStatus(action)
(DesignOrder) -> (Notification): sendToBuyer(status)
@enduml
