@startuml
actor Pembeli
boundary PrintParametersPage
control PriceEstimator

PrintParametersPage -> PriceEstimator : calculate(params)
activate PriceEstimator
PriceEstimator --> PrintParametersPage : estimatedPrice
deactivate PriceEstimator
PrintParametersPage --> Pembeli : displayPrice(estimatedPrice)
deactivate PrintParametersPage
@enduml
