@startuml
skinparam backgroundColor transparent
boundary ShippingPage
control ShippingCostCalculator
entity Order

(ShippingPage) -> (ShippingCostCalculator): calculate(address, courier)
(ShippingPage) -> (Order): addShippingCost(shippingCost)
@enduml
