@startuml
skinparam backgroundColor transparent
|Pembeli|
start
:Memilih desain yang sudah diunggah;
:Mengatur parameter (filamen, layer, warna, etc);
|Sistem|
:Simpan;
:Menampilkan hasil penyesuaian;
|Pembeli|
stop
@enduml
