@startuml
|Pembeli|
start
:Mengisi form pendaftaran (email, password, dll);
|Sistem|
:Validasi data;
:Mengirim link konfirmasi ke email;
|Pembeli|
:Membuka email dan klik link konfirmasi;
|Sistem|
:Verifikasi token konfirmasi;
:Simpan data akun pembeli;
:Menampilkan notifikasi pendaftaran berhasil;
stop
@enduml