@startuml
actor Pembeli
boundary SignUpPage
entity Account

Pembeli -> SignUpPage : submit(data_pendaftaran)
activate SignUpPage
SignUpPage -> Account : create(data_pendaftaran)
activate Account
Account --> SignUpPage : success()
deactivate Account
SignUpPage --> Pembeli : Tampilkan halaman konfirmasi
deactivate SignUpPage
@enduml